In [1]:
import numpy as np

In [2]:
a = np.arange(0, 20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
a.shape

(20,)

In [4]:
a[0]

0

In [5]:
a[3]

3

In [14]:
a = a.reshape(2, 10)
a.shape

(2, 10)

In [15]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [16]:
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a[-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
a[0][3]

3

In [23]:
a = a.reshape(2, 5, 2)
a.shape

(2, 5, 2)

In [24]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [28]:
a[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
a[0][3]

array([6, 7])

In [30]:
a[0][3][1]

7

In [54]:
b = np.arange(0, 40, 2).reshape(4, 5)
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [36]:
pytnon_list = [x**2 for x in range(10)]
pytnon_list

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [37]:
c = np.array(pytnon_list)
c

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [41]:
zero_array = np.zeros(10)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
one_array = np.ones(10)
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
empty_array = np.empty(100)
empty_array

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.46196864e-311, 1.46196864e-311, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

In [45]:
lucky_array = np.full((5, 5), 13)
lucky_array

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [47]:
diagonal_array = np.eye(5)
diagonal_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
random_array = np.random.random(10)
random_array

array([0.7543595 , 0.06441588, 0.63294622, 0.77715855, 0.20600779,
       0.76775038, 0.31548242, 0.75004517, 0.51112727, 0.69245294])

In [52]:
linspace_array = np.linspace(100, 200, 5)
linspace_array

array([100., 125., 150., 175., 200.])