In [1]:
import numpy as np

In [2]:
arr = np.arange(5, 30, 2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [12]:
boolArr = [True if x < 10 else False for x in arr]
boolArr

[True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [14]:
boolArr = arr < 10
boolArr

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [15]:
newArr = arr[boolArr]
newArr

array([5, 7, 9])

In [17]:
newArr = arr[arr%3==0]
newArr

array([ 9, 15, 21, 27])

In [18]:
newArr = arr[(arr > 5) & (arr < 20)]
newArr

array([ 7,  9, 11, 13, 15, 17, 19])

In [5]:
for number, bool in zip(arr, boolArr):
    if bool == True:
        print(number)

5
7
9


In [6]:
for number, bool in zip(arr, boolArr):
    if number < 20:
        print(number)

5
7
9
11
13
15
17
19


In [7]:
for number, bool in zip(arr, boolArr):
    if number % 3 == 0:
        print(number)

9
15
21
27


In [8]:
for number, bool in zip(arr, boolArr):
    if number > 10 and number < 20:
        print(number)

11
13
15
17
19


In [20]:
arr = np.arange(24).reshape(4, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
arr[0]

array([0, 1, 2, 3, 4, 5])

In [23]:
arr[0,2:4]

array([2, 3])

In [24]:
arr[0, 2:5]

array([2, 3, 4])

In [25]:
arr[0,:]

array([0, 1, 2, 3, 4, 5])

In [26]:
arr[:, 1]

array([ 1,  7, 13, 19])

In [33]:
arr[0:2, 2]

array([2, 8])

In [34]:
arr[:2,1]

array([1, 7])

In [35]:
arr[:2,2:4]

array([[2, 3],
       [8, 9]])

In [36]:
arr[:, -1]

array([ 5, 11, 17, 23])

In [37]:
arr[:,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [38]:
arr = np.arange(50).reshape(10, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [42]:
split_level = 0.2
num_rows = arr.shape[0]
split_border = split_level * num_rows
np.random.shuffle(arr)

In [43]:
arr[:round(split_border)]

array([[ 0,  1,  2,  3,  4],
       [35, 36, 37, 38, 39]])

In [44]:
arr[round(split_border):]

array([[15, 16, 17, 18, 19],
       [40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [45, 46, 47, 48, 49],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
X_learn = arr[round(split_border):, :-1]
X_learn

array([[15, 16, 17, 18],
       [40, 41, 42, 43],
       [25, 26, 27, 28],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [45, 46, 47, 48],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [52]:
y_learn = arr[round(split_border):,-1]
y_learn

array([19, 44, 29, 24, 34, 49,  9, 14])

In [55]:
X_test = arr[:round(split_border), :-1]
X_test

array([[ 0,  1,  2,  3],
       [35, 36, 37, 38]])

In [57]:
y_test = arr[:round(split_border), -1]
y_test

array([ 4, 39])