In [1]:
import numpy as np

In [6]:
X = np.arange(1, 26).reshape(5, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
Ones = np.ones(shape=(5, 5))
Ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.dot(X, Ones)

array([[ 15.,  15.,  15.,  15.,  15.],
       [ 40.,  40.,  40.,  40.,  40.],
       [ 65.,  65.,  65.,  65.,  65.],
       [ 90.,  90.,  90.,  90.,  90.],
       [115., 115., 115., 115., 115.]])

In [16]:
diag = np.zeros(shape=(5, 5))
np.fill_diagonal(diag, val=1)
diag

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.dot(X, diag)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [18]:
np.where(X > 10, 1, 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.where(X % 2 == 0, 1, 0)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [20]:
np.where(X % 2 == 0, 1, X + 1)

array([[ 2,  1,  4,  1,  6],
       [ 1,  8,  1, 10,  1],
       [12,  1, 14,  1, 16],
       [ 1, 18,  1, 20,  1],
       [22,  1, 24,  1, 26]])

In [21]:
X_bis = np.where(X > 10, X * 2, 0)
X_bis

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [22]:
np.count_nonzero(X_bis)

15

In [23]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])

In [26]:
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [27]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100, 200, 300]])

In [28]:
print(np.append(x, y, axis=0))

[[ 10  20  30]
 [ 40  50  60]
 [100 200 300]]


In [30]:
print(np.append(x, x, axis=0))

[[10 20 30]
 [40 50 60]
 [10 20 30]
 [40 50 60]]
