In [1]:
import numpy as np

In [3]:
X =  np.arange(-25, 25).reshape(10, 5)
X

array([[-25, -24, -23, -22, -21],
       [-20, -19, -18, -17, -16],
       [-15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [5]:
ones = np.ones(shape=(10, 1))
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [7]:
X_1 = np.append(X, ones, axis=1)
X_1

array([[-25., -24., -23., -22., -21.,   1.],
       [-20., -19., -18., -17., -16.,   1.],
       [-15., -14., -13., -12., -11.,   1.],
       [-10.,  -9.,  -8.,  -7.,  -6.,   1.],
       [ -5.,  -4.,  -3.,  -2.,  -1.,   1.],
       [  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.]])

In [8]:
len(X_1[0])

6

In [14]:
w = np.random.randn(len(X_1[0]))
w

array([-0.02462945,  0.88972567,  0.71813593,  0.21949208,  0.16153278,
        1.694775  ])

In [11]:
def predict(x, w):
    total_simulation = np.dot(x, w)
    return 1 if total_simulation > 0 else -1

In [12]:
predict(X_1[0], w)

1

In [15]:
for x in X_1:
    print(predict(x, w))

-1
-1
-1
-1
-1
1
1
1
1
1
